server:
  servlet:
    context-path: /

logging:
  level:
    com.spring.example: DEBUG
    org.springframework.web: INFO
    reactor.netty.http.client: INFO

spring:
  mvc:
    log-request-details: true
