server:
  servlet:
    context-path: /web

logging:
  level:
    org.springframework.web: INFO
    com.spring.webflux: INFO
    reactor.netty.http.client: INFO
    com.spring: DEBUG

spring:
  mvc:
    log-request-details: true
